---
title: "Chapter 4"
output: html_notebook
---

# Chapter

```{r setup, results = FALSE}
library(rethinking)
library(tidyverse)

```

```{r}
data(Howell1)
d <- Howell1
d2 <- d %>% 
  filter( age >= 18 )

precis( d2 , hist = FALSE)

curve( dnorm( x, 178, 20), from=100, to=250) 

```

```{r}
flist <- alist(  height ~ dnorm( mu, sigma),
                 mu ~ dnorm( 178, 20),  
                 sigma ~ dunif( 0, 50)  ) 

m4_1 <- quap(flist, data = d2)

precis( m4_1 )

```

```{r}
ggplot(d2, aes(x = weight, y = height)) +
  geom_point() +
  theme_minimal()
```

```{r}

xbar <- mean(d2$weight)

m4_3 <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a + b*( weight - xbar ) ,
    a ~ dnorm( 178 , 20 ) ,
    b ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 50 )
  ), 
  data = d2) 

```

# Exercises

#### M1

For the model definition below, simulate observed values from the prior (not the posterior).

```{r}
rows <- 1000
mu <- rnorm(rows, 0, 10)
sigma <- rexp(rows, 1)
y <- rnorm(rows, mu, sigma)
dens(y)

```

#### M2

Translate the model just above into a `quap` formula.

```{r}
formula <- alist(
  y ~ dnorm(mu, sigma) ,
  mu ~ dnorm(0, 10) ,
  sigma ~ dexp(1)
)
```

#### M3

Translate the `quap` model formula below into a mathematical model definition.

$$
y_i \sim \text{Normal}(\mu,\sigma) \\
\mu_i = \alpha + \beta x \\
\alpha \sim \text{Normal}(0,10) \\
\beta \sim \text{Uniform}(0,1) \\
\sigma \sim \text{Exponential}(1)
$$

#### M4

$$
y_i \sim \text{Normal}(\mu, \sigma) \\
\mu_i = \alpha + \beta \text{year} \\
\alpha \sim \text{Normal}(66,4) \\
\beta \sim \text{Uniform}(0,1) \\
\sigma \sim \text{Exponential}(1)
$$

# Class

Two types of rescaling

-   Z-scores

```{r}
d$zweight <- as.numeric(scale(d$weight))
d$zheight <- as.numeric(scale(d$height))

formula <- alist(
  zheight ~ dnorm(mu, sigma),
  mu <- a + b*zweight,
  a ~ dnorm(0,.0001),
  b ~ dnorm(0,1),
  sigma ~ dexp(1)
)

c1 <- quap(formula, d)
precis(c1)

```

-   Min/max

```{r}
d$weight01 <- (d$weight - min(d$weight)) / 
  (max(d$weight) - min(d$weight))

d$height01 <- (d$height - min(d$height)) / 
  (max(d$height) - min(d$height))

formula <- alist(
  height01 ~ dnorm(mu, sigma),
  mu <- a + b*weight01,
  a ~ dnorm(0,1),
  b ~ dnorm(0,1),
  sigma ~ dexp(2)
)

c2 <- quap(formula, d)
precis(c2)

```

CURVES

-   Z-scores

```{r}
d$zweight <- as.numeric(scale(d$weight))
d$zheight <- as.numeric(scale(d$height))

formula <- alist(
  zheight ~ dnorm(mu, sigma),
  mu <- a + b1*zweight + b2*zweight^2 ,
  a ~ dnorm(0,1),
  b1 ~ dnorm(0,1),
  b2 ~ dnorm(0,1),
  sigma ~ dexp(1)
)

c3 <- quap(formula, d)
precis(c3)

```

-   Min/max

```{r}
d$weight01 <- (d$weight - min(d$weight)) / 
  (max(d$weight) - min(d$weight))

d$height01 <- (d$height - min(d$height)) / 
  (max(d$height) - min(d$height))

formula <- alist(
  height01 ~ dnorm(mu, sigma),
  mu <- a + b1*weight01 + b2*weight01^2,
  a ~ dnorm(0,1),
  b1 ~ dnorm(0,1),
  b2 ~ dnorm(0,1),
  sigma ~ dexp(2)
)

c4 <- quap(formula, d)
precis(c4)

```
