---
title: "SR 9 Demo"
author: "Steve Vaisey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rethinking)
library(rstanarm)
# options(mc.cores = parallel::detectCores())
# the above actually slows it down on a small df
```

```{r}
data("Howell1")
d <- Howell1 |> 
  filter(age >= 18)
```

```{r}
m1 <- stan_glm(weight ~ height * male + age,
               prior = normal(0, 2.5, autoscale = TRUE),
               prior_intercept = normal(0, 2.5, autoscale = TRUE),
               prior_aux = exponential(1, autoscale = TRUE),
               data = d)
```

#### diagnostics the easy way

```{r}
launch_shinystan(m1)
```

#### get draws if you want

```{r}
m1draws <- tidybayes::tidy_draws(m1)

m1estimates <- m1draws |> 
  janitor::clean_names() |> 
  select(chain, draw, height, male, height_male) |> 
  pivot_longer(height:height_male,
               names_to = "term",
               values_to = "estimate")

## you could go on to plot these if you wanted

```


```{r}
library(modelsummary)

# table
msummary(m1, 
         statistic = "conf.int",
         conf_level = .89)
```

```{r}
library(ggeffects)
ggpredict(m1,
          terms = c("height", 
                    "male"),
          ci.lvl = .89) |> 
  plot()
```
